// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | AboutSectionSlice
  | EventsSectionSlice
  | ServicesSectionSlice
  | ArchitectureofChangeSectionSlice
  | WhatShiftsSectionSlice
  | HowSectionSlice
  | WhySectionSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Primary content in *AboutSection → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Info field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;

  /**
   * Image field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Bio Image field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.bio_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bio_image: prismic.ImageField<never>;

  /**
   * Bio Info field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.bio_info
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio_info: prismic.RichTextField;

  /**
   * Name field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Occupation field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.occupation
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  occupation: prismic.KeyTextField;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Item in *ArchitectureofChangeSection → Default → Primary → Circular Timeline Items*
 */
export interface ArchitectureofChangeSectionSliceDefaultPrimaryCircularTimelineItemsItem {
  /**
   * Title field in *ArchitectureofChangeSection → Default → Primary → Circular Timeline Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: architectureof_change_section.default.primary.circular_timeline_items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *ArchitectureofChangeSection → Default → Primary → Circular Timeline Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: architectureof_change_section.default.primary.circular_timeline_items[].info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;
}

/**
 * Primary content in *ArchitectureofChangeSection → Default → Primary*
 */
export interface ArchitectureofChangeSectionSliceDefaultPrimary {
  /**
   * Title field in *ArchitectureofChangeSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: architectureof_change_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *ArchitectureofChangeSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: architectureof_change_section.default.primary.info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;

  /**
   * Circular Timeline Items field in *ArchitectureofChangeSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: architectureof_change_section.default.primary.circular_timeline_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  circular_timeline_items: prismic.GroupField<
    Simplify<ArchitectureofChangeSectionSliceDefaultPrimaryCircularTimelineItemsItem>
  >;
}

/**
 * Default variation for ArchitectureofChangeSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArchitectureofChangeSectionSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<ArchitectureofChangeSectionSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *ArchitectureofChangeSection*
 */
type ArchitectureofChangeSectionSliceVariation =
  ArchitectureofChangeSectionSliceDefault;

/**
 * ArchitectureofChangeSection Shared Slice
 *
 * - **API ID**: `architectureof_change_section`
 * - **Description**: ArchitectureofChangeSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArchitectureofChangeSectionSlice = prismic.SharedSlice<
  "architectureof_change_section",
  ArchitectureofChangeSectionSliceVariation
>;

/**
 * Item in *EventsSection → Default → Primary → Events*
 */
export interface EventsSectionSliceDefaultPrimaryEventsItem {
  /**
   * Banner field in *EventsSection → Default → Primary → Events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.events[].banner
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  banner: prismic.ImageField<never>;

  /**
   * Title field in *EventsSection → Default → Primary → Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.events[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *EventsSection → Default → Primary → Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.events[].info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;

  /**
   * Venue field in *EventsSection → Default → Primary → Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.events[].venue
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  venue: prismic.KeyTextField;

  /**
   * Date field in *EventsSection → Default → Primary → Events*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.events[].date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Time field in *EventsSection → Default → Primary → Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.events[].time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;

  /**
   * Event Link field in *EventsSection → Default → Primary → Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.events[].event_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  event_link: prismic.KeyTextField;
}

/**
 * Primary content in *EventsSection → Default → Primary*
 */
export interface EventsSectionSliceDefaultPrimary {
  /**
   * Intro Info field in *EventsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.intro_info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro_info: prismic.KeyTextField;

  /**
   * Title field in *EventsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *EventsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;

  /**
   * Events field in *EventsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.events[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  events: prismic.GroupField<
    Simplify<EventsSectionSliceDefaultPrimaryEventsItem>
  >;
}

/**
 * Default variation for EventsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventsSection*
 */
type EventsSectionSliceVariation = EventsSectionSliceDefault;

/**
 * EventsSection Shared Slice
 *
 * - **API ID**: `events_section`
 * - **Description**: EventsSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventsSectionSlice = prismic.SharedSlice<
  "events_section",
  EventsSectionSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Switching Texts*
 */
export interface HeroSliceDefaultPrimarySwitchingTextsItem {
  /**
   * Text field in *Hero → Default → Primary → Switching Texts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.switching_texts[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;

  /**
   * Switching Texts field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.switching_texts[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  switching_texts: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimarySwitchingTextsItem>
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *HowSection → Default → Primary → How Items*
 */
export interface HowSectionSliceDefaultPrimaryHowItemsItem {
  /**
   * Image field in *HowSection → Default → Primary → How Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_section.default.primary.how_items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *HowSection → Default → Primary → How Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_section.default.primary.how_items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *HowSection → Default → Primary → How Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_section.default.primary.how_items[].info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;
}

/**
 * Primary content in *HowSection → Default → Primary*
 */
export interface HowSectionSliceDefaultPrimary {
  /**
   * Top Text field in *HowSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_section.default.primary.top_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  top_text: prismic.KeyTextField;

  /**
   * Intro Title field in *HowSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_section.default.primary.intro_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro_title: prismic.KeyTextField;

  /**
   * Intro Text field in *HowSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_section.default.primary.intro_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro_text: prismic.KeyTextField;

  /**
   * How Items field in *HowSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: how_section.default.primary.how_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  how_items: prismic.GroupField<
    Simplify<HowSectionSliceDefaultPrimaryHowItemsItem>
  >;

  /**
   * Extra Section Tag Text field in *HowSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_section.default.primary.extra_section_tag_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  extra_section_tag_text: prismic.KeyTextField;

  /**
   * Extra Section Info field in *HowSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_section.default.primary.extra_section_info
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  extra_section_info: prismic.RichTextField;
}

/**
 * Default variation for HowSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HowSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HowSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HowSection*
 */
type HowSectionSliceVariation = HowSectionSliceDefault;

/**
 * HowSection Shared Slice
 *
 * - **API ID**: `how_section`
 * - **Description**: HowSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HowSectionSlice = prismic.SharedSlice<
  "how_section",
  HowSectionSliceVariation
>;

/**
 * Item in *ServicesSection → Default → Primary → Services*
 */
export interface ServicesSectionSliceDefaultPrimaryServicesItem {
  /**
   * Card Title field in *ServicesSection → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.services[].card_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_title: prismic.KeyTextField;

  /**
   * Card Info field in *ServicesSection → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.services[].card_info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_info: prismic.KeyTextField;

  /**
   * Image field in *ServicesSection → Default → Primary → Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.services[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Tag Text field in *ServicesSection → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.services[].tag_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag_text: prismic.KeyTextField;

  /**
   * Full Title field in *ServicesSection → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.services[].full_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  full_title: prismic.KeyTextField;

  /**
   * Full Info field in *ServicesSection → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.services[].full_info
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  full_info: prismic.RichTextField;

  /**
   * Features Title field in *ServicesSection → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.services[].features_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  features_title: prismic.KeyTextField;

  /**
   * Features List field in *ServicesSection → Default → Primary → Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.services[].features_list
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  features_list: prismic.RichTextField;

  /**
   * Button Text field in *ServicesSection → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.services[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Primary content in *ServicesSection → Default → Primary*
 */
export interface ServicesSectionSliceDefaultPrimary {
  /**
   * Title field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;

  /**
   * Services field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services: prismic.GroupField<
    Simplify<ServicesSectionSliceDefaultPrimaryServicesItem>
  >;
}

/**
 * Default variation for ServicesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesSection*
 */
type ServicesSectionSliceVariation = ServicesSectionSliceDefault;

/**
 * ServicesSection Shared Slice
 *
 * - **API ID**: `services_section`
 * - **Description**: ServicesSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSectionSlice = prismic.SharedSlice<
  "services_section",
  ServicesSectionSliceVariation
>;

/**
 * Item in *WhatShiftsSection → Default → Primary → Dropdown Items*
 */
export interface WhatShiftsSectionSliceDefaultPrimaryDropdownItemsItem {
  /**
   * Title field in *WhatShiftsSection → Default → Primary → Dropdown Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_shifts_section.default.primary.dropdown_items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *WhatShiftsSection → Default → Primary → Dropdown Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_shifts_section.default.primary.dropdown_items[].info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;
}

/**
 * Primary content in *WhatShiftsSection → Default → Primary*
 */
export interface WhatShiftsSectionSliceDefaultPrimary {
  /**
   * Title field in *WhatShiftsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_shifts_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *WhatShiftsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_shifts_section.default.primary.info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;

  /**
   * Dropdown Items field in *WhatShiftsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: what_shifts_section.default.primary.dropdown_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  dropdown_items: prismic.GroupField<
    Simplify<WhatShiftsSectionSliceDefaultPrimaryDropdownItemsItem>
  >;

  /**
   * Image field in *WhatShiftsSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: what_shifts_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for WhatShiftsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhatShiftsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhatShiftsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhatShiftsSection*
 */
type WhatShiftsSectionSliceVariation = WhatShiftsSectionSliceDefault;

/**
 * WhatShiftsSection Shared Slice
 *
 * - **API ID**: `what_shifts_section`
 * - **Description**: WhatShiftsSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhatShiftsSectionSlice = prismic.SharedSlice<
  "what_shifts_section",
  WhatShiftsSectionSliceVariation
>;

/**
 * Primary content in *WhySection → Default → Primary*
 */
export interface WhySectionSliceDefaultPrimary {
  /**
   * Left Text field in *WhySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_section.default.primary.left_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  left_text: prismic.KeyTextField;

  /**
   * Image field in *WhySection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: why_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Central Text field in *WhySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_section.default.primary.central_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  central_text: prismic.KeyTextField;
}

/**
 * Default variation for WhySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhySectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhySectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhySection*
 */
type WhySectionSliceVariation = WhySectionSliceDefault;

/**
 * WhySection Shared Slice
 *
 * - **API ID**: `why_section`
 * - **Description**: WhySection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhySectionSlice = prismic.SharedSlice<
  "why_section",
  WhySectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      ArchitectureofChangeSectionSlice,
      ArchitectureofChangeSectionSliceDefaultPrimaryCircularTimelineItemsItem,
      ArchitectureofChangeSectionSliceDefaultPrimary,
      ArchitectureofChangeSectionSliceVariation,
      ArchitectureofChangeSectionSliceDefault,
      EventsSectionSlice,
      EventsSectionSliceDefaultPrimaryEventsItem,
      EventsSectionSliceDefaultPrimary,
      EventsSectionSliceVariation,
      EventsSectionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimarySwitchingTextsItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HowSectionSlice,
      HowSectionSliceDefaultPrimaryHowItemsItem,
      HowSectionSliceDefaultPrimary,
      HowSectionSliceVariation,
      HowSectionSliceDefault,
      ServicesSectionSlice,
      ServicesSectionSliceDefaultPrimaryServicesItem,
      ServicesSectionSliceDefaultPrimary,
      ServicesSectionSliceVariation,
      ServicesSectionSliceDefault,
      WhatShiftsSectionSlice,
      WhatShiftsSectionSliceDefaultPrimaryDropdownItemsItem,
      WhatShiftsSectionSliceDefaultPrimary,
      WhatShiftsSectionSliceVariation,
      WhatShiftsSectionSliceDefault,
      WhySectionSlice,
      WhySectionSliceDefaultPrimary,
      WhySectionSliceVariation,
      WhySectionSliceDefault,
    };
  }
}
