// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  affirmations_section: dynamic(() => import("./AffirmationsSection")),
  architectureof_change_section: dynamic(
    () => import("./ArchitectureofChangeSection"),
  ),
  events_section: dynamic(() => import("./EventsSection")),
  faqs_section: dynamic(() => import("./FaqsSection")),
  hero: dynamic(() => import("./Hero")),
  how_section: dynamic(() => import("./HowSection")),
  ig_feed_section: dynamic(() => import("./IgFeedSection")),
  reviews_section: dynamic(() => import("./ReviewsSection")),
  services_section: dynamic(() => import("./ServicesSection")),
  what_shifts_section: dynamic(() => import("./WhatShiftsSection")),
  why_section: dynamic(() => import("./WhySection")),
};
