// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  architectureof_change_section: dynamic(
    () => import("./ArchitectureofChangeSection"),
  ),
  events_section: dynamic(() => import("./EventsSection")),
  hero: dynamic(() => import("./Hero")),
  how_section: dynamic(() => import("./HowSection")),
  services_section: dynamic(() => import("./ServicesSection")),
  what_shifts_section: dynamic(() => import("./WhatShiftsSection")),
  why_section: dynamic(() => import("./WhySection")),
};
